import requests
from config import GITHUB_TOKEN, OWNER, REPO

headers = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

def create_pull_request(issue_number):

    branch = f"agent-fix-issue-{issue_number}"

    # Check if PR already exists
    check_url = f"https://api.github.com/repos/{OWNER}/{REPO}/pulls?head={OWNER}:{branch}"

    check = requests.get(check_url, headers=headers)

    if check.status_code == 200 and len(check.json()) > 0:
        print("Pull Request already exists. Skipping creation.")
        return

    url = f"https://api.github.com/repos/{OWNER}/{REPO}/pulls"

    data = {
        "title": f"Auto Fix for Issue #{issue_number}",
        "body": "Fix generated by autonomous agent",
        "head": branch,
        "base": "main"
    }

    response = requests.post(url, json=data, headers=headers)

    if response.status_code == 201:
        print("Pull Request Created Successfully!")
    else:
        print("PR creation failed:", response.json())